#!/usr/bin/env python
"""Redshift GUI."""

import sys
import subprocess
import Tkinter


class RedshiftController(object):
    def __init__(self):
        pass
        self.neutral = 6500
        self.val = self.neutral
        self.min = 1000
        self.max = 25000

    def adjust(self, delta):
        """
        Args:
            delta: Amount to change by in K.
        """
        self.val += delta
        self.val = max(self.min, min(self.val, self.max))
        self.apply()

    def apply(self):
        sub = subprocess.Popen(["redshift", "-O", str(self.val)])
        sub.communicate()
        print self.val


class RedshiftGUI(Tkinter.Frame, object):
    def __init__(self, parent):
        super(RedshiftGUI, self).__init__(parent)
        self.controller = RedshiftController()
        self.controller.apply()
        self.macro_increment = 2000
        self.micro_increment = 250

        # Keyboard shortcuts for quit.
        for keys in ["<Return>", "<Control-q>", "<Control-c>", "<Control-w>"]:
            parent.bind_all(keys, lambda *args: self.on_kb_quit())

        parent.bind("<Up>", lambda *args: self.on_up())
        parent.bind("<Down>", lambda *args: self.on_down())
        parent.bind("<Left>", lambda *args: self.on_left())
        parent.bind("<Right>", lambda *args: self.on_right())

        self.label_temp = Tkinter.Label(self, text="")
        self.label_temp.grid(sticky=Tkinter.N)

        self.pack()
        self.update()

    def update(self):
        text = "{}K".format(self.controller.val)
        self.label_temp.config(text=text)

    def on_kb_quit(self):
        sys.exit(0)

    def on_up(self):
        self.controller.adjust(self.micro_increment)
        self.update()

    def on_down(self):
        self.controller.adjust(-self.micro_increment)
        self.update()

    def on_left(self):
        self.controller.adjust(-self.macro_increment)
        self.update()

    def on_right(self):
        self.controller.adjust(self.macro_increment)
        self.update()


if __name__ == "__main__":
    root = Tkinter.Tk()
    RedshiftGUI(root)
    root.mainloop()
